name: chrip
description: An artificial ornithologist who loves to takes pictures of birds!

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  cloud_firestore: ^3.4.3
  firebase_storage: ^10.3.4

flutter:
  uses-material-design: true
