// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCica8K0NwZFph2RBvtRGlykSodtcGrNFk',
    appId: '1:751629403785:web:0fb4cb15096904d86ee858',
    messagingSenderId: '751629403785',
    projectId: 'firstloginout',
    authDomain: 'firstloginout.firebaseapp.com',
    storageBucket: 'firstloginout.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEsauEE8N2RMUiOUFFqGgmnVvUpaXdaVA',
    appId: '1:751629403785:android:a945932fd2306b236ee858',
    messagingSenderId: '751629403785',
    projectId: 'firstloginout',
    storageBucket: 'firstloginout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF7vy--2VqxITfvJ2BIV4lWJbScJzoGFg',
    appId: '1:751629403785:ios:58e95d46f8f7818f6ee858',
    messagingSenderId: '751629403785',
    projectId: 'firstloginout',
    storageBucket: 'firstloginout.appspot.com',
    iosClientId: '751629403785-h25pteb137mg39b1cg5mh0s4p7ubjmki.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF7vy--2VqxITfvJ2BIV4lWJbScJzoGFg',
    appId: '1:751629403785:ios:58e95d46f8f7818f6ee858',
    messagingSenderId: '751629403785',
    projectId: 'firstloginout',
    storageBucket: 'firstloginout.appspot.com',
    iosClientId: '751629403785-h25pteb137mg39b1cg5mh0s4p7ubjmki.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginui',
  );
}
